### ISSUE TITLE
Error: unhandled exception: nimpress.nim(122, 12) `x >= 0.0 and x <= 1.0`  [AssertionError]

### ISSUE THREAD

**Issue by ewilkie** [mpinese/nimpress#11]
Nimble test - ok no errors

Get this error through

./nimpress Vijayakrishnan_Houlston_2018_NatCom_output_BCP-ALL_NIMPRESS_input.txt landscape.germline_hc.merged_subvars.bcf > out.txt

fatal.nim(39)            sysFatal
Error: unhandled exception: nimpress.nim(122, 12) `x >= 0.0 and x <= 1.0`  [AssertionError]

Vijayakrishnan_Houlston_2018_NatCom_output_BCP-ALL_NIMPRESS_input.txt 

Vijayakrishnan + Houlston 2018 NatCom 
Supplementary Table 11. Individual variance in risk associated with childhood BCP-ALL SNPs 
DOI: 10.1038/ncomms4856 PMID: 29632299 DOI: 10.1038/s41467-018-03178-z 
GRCh37 
0.0
2	146124454	C	A	0.7608058	NaN
7	50477144	G	A	0.5596158	NaN
8	130194104	C	A	0.2851789	NaN
9	21970916	C	G	0.9745596	NaN
9	21984661	A	C	0.356674943938732	NaN
10	63723577	C	C	-0.6348783	NaN
10	8101927	T	C	0.2926696	NaN
10	22856279	C	C	-0.2357223	NaN
10	126294480	C	T	0.2311117	NaN
14	23589349	A	C	-0.3147107	NaN
12	96614125	C	T	0.1906204	NaN

**Comment by mpinese** [comment]
Ok cool I can work with that, thanks.

And don't worry about the plink2 - on my roadmap anyway, and shouldn't be
too hard (famous last words alert)
